### ISSUE TITLE
"Out of Memory" Error

### ISSUE THREAD

**Issue by kpsledge** [gimjudge/php#2]
Hi, 

I've been trying to run the 5.6.30 version of the php_printer.dll and upon the printer_open() function, I get 

Fatal error: Out of memory (allocated 262144) (tried to allocate 4294967295 bytes) in <php file>

We've used this dll in pass php versions and did not have this issue.  Any help would be greatly appreciated.  We are running on Windows Server 2016, IIS in FastCGI mode

PHP Version 5.6.30, MSVC11 x86 - Thread Safe.

Thanks,

**Comment by gimjudge** [comment]
Sorry, I'm not working for the company I set this up for. 
https://community.apachefriends.org/viewtopic.php?f=16&t=75496&p=256058#p256058

Please look at this link to see if you can find help.

**Comment by Yarli** [comment]
I think your supposed to run NTS not TS version of PHP on IIS, which might explain why your getting this error.
I think the library on here is the TS version, which is more designed for Apache i think.

I've got version 5.6.35 on my repo at https://github.com/Yarli/php_printer if that helps ? 
Will mean you need to upgrade to that version of PHP, and i've compiled both the TS and NTS versions, but would advise using the NTS one with the NTS version of PHP if your running this via FastCGI on IIS.
