### ISSUE TITLE
Need dll for php 5.6.31 x64

### ISSUE THREAD

**Issue by VaporFan** [gimjudge/php#3]
Hello,
Could you please release the dll for x64 ?

**Comment by gimjudge** [comment]
https://community.apachefriends.org/viewtopic.php?f=16&t=75496&p=256058#p256058

I no longer work for the company that was using this. If the above link doesn't give you the information you need to do it yourself let me know. I don't have a way to test it if I create it for you nor would I be getting paid for it.
