### ISSUE TITLE
Need builds

### ISSUE THREAD

**Issue by VaporFan** [gimjudge/php#4]
Could you make some more effort to update these dll to the latest php version? Thankss

**Comment by Yarli** [comment]
I'm working on doing some more builds of these and putting them up on my repo as I don;t have access to upload here.

I've put up 5.6.35 already, which was the latest build of 5.6 that PHP released.
My Repo is at: https://github.com/Yarli/php_printer
I'm aiming to get a 7.1 version up but not sure how far i'll get on with that.
Haven't done 7.2 yet the process for building it is different and haven't yet setup my environment for this.

Your always welcome to have a go at building this yourself.
Pretty good instructions for building this is available at:
https://community.apachefriends.org/viewtopic.php?f=16&t=70797

**Comment by gimjudge** [comment]
Thanks Yarli.
I no longer work for the company that used php_printer. Sadly, I wasn't doing this just for fun!
