### ISSUE TITLE
Install in shared hosting

### ISSUE THREAD

**Issue by kevingio** [gimjudge/php#5]
Hi, 
How do I install this .dll files if I use shared hosting?

**Comment by Yarli** [comment]
Short and only answer is "You can't."
These DLL files only allow **the server** to access a printer which is on a network that the server can talk to. 
Even if you had access to the server environment and were able to add the dll to the php.ini file, I suspect that the shared hosting server is likely outside of your network and therefore won't have access to your printer anyway.

What I suspect you need is more a PDF driven solution, which generates a PDF file, presents this to your user as a pdf document, which should automatically open on the users browser, and then there is some javascript which you can embed into that PDF which automatically opens the print dialog window.

Hope that helps.

**Comment by kevingio** [comment]
Thanks for the explanation. Can I print pdf file to a POS printer or maybe you have other advices for me? Im new in php, thanks in advance.

**Comment by Yarli** [comment]
Without knowing the exact setup it's hard to offer an perfect solution, but I would say that the PDF route or even a pure HTML/javascript based solution will work.

Basically open a new window and point it to the url of the PHP file. The PHP file then generates the output that you want to print.
Then use javascript to open the Print dialog window. I beleive that's just 
`window.print();`
This obviously means you need the POS printer installed on the machine which the user is using to call the PHP file from. And you'll obviosuly need to setup the page layout in the web browser settings too, as I suspect you won;t be printing to normal A4 or US Letter sized paper, but instead a continous media like a till receipt etc.

To be honest your question is a bit out of scope for this project, so I would perhaps pose your question up on www.stackoverflow.com which you will probably have more luck with getting an answer on.

**Comment by kevingio** [comment]
Oh I see, I will try to use window.print() and do some layouting. Anyway, thanks for your response, really appreciate it.
